---
title: "FML_Assignment - 1"
author: "Srikanth Chetlapally"
date: "2024-02-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importing the dataset into R

# Source: Kaggle (<https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques?rvi=1>)

library(readr)  
data <- read_csv("house_prices.csv")  
str(data)  

# Summary statistics for quantitative variables

summary(data$SalePrice)      
summary(data$LotArea)     

# Frequency table for a categorical variable ('Neighborhood')

table(data$Neighborhood)

# Transforming a quantitative variable (logarithm of 'LotArea')

data$log_LotArea <- log(data$LotArea)

# Ploting a histogram for a quantitative variable (SalePrice)

hist(data$SalePrice, main = "Histogram of Sale Price", xlab = "Sale Price")

# Creating a scatterplot (LotArea vs. SalePrice)

plot(data$LotArea,data$SalePrice, main = "Scatterplot", xlab = "Lot Area", ylab = "Sale Price")

```
